In [1]:
#Multiple Regression Model
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("/content/Salary_Data_1.csv")
data.head()

YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Age              30 non-null     float64
 2   Salary           30 non-null     int64  
dtypes: float64(2), int64(1)
memory usage: 848.0 bytes


In [4]:
data.head()

YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891

In [5]:
data.isnull().sum()

YearsExperience    0
Age                0
Salary             0
dtype: int64

In [6]:
len(data)

30

In [26]:
import pandas as pd
X=data[['YearsExperience','Age']]
X.values

array([[ 1.1, 21. ],
       [ 1.3, 21.5],
       [ 1.5, 21.7],
       [ 2. , 22. ],
       [ 2.2, 22.2],
       [ 2.9, 23. ],
       [ 3. , 23. ],
       [ 3.2, 23.3],
       [ 3.2, 23.3],
       [ 3.7, 23.6],
       [ 3.9, 23.9],
       [ 4. , 24. ],
       [ 4. , 24. ],
       [ 4.1, 24. ],
       [ 4.5, 25. ],
       [ 4.9, 25. ],
       [ 5.1, 26. ],
       [ 5.3, 27. ],
       [ 5.9, 28. ],
       [ 6. , 29. ],
       [ 6.8, 30. ],
       [ 7.1, 30. ],
       [ 7.9, 31. ],
       [ 8.2, 32. ],
       [ 8.7, 33. ],
       [ 9. , 34. ],
       [ 9.5, 35. ],
       [ 9.6, 36. ],
       [10.3, 37. ],
       [10.5, 38. ]])

In [13]:
y = data['Salary'].values
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872])

In [14]:
y.shape

(30,)

In [33]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=200)

In [34]:
#### Build the model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [35]:
### Perform Training 
model.fit(xtrain,ytrain)

LinearRegression()

In [36]:
### Perform Training 
model.fit(X,y)

LinearRegression()

In [37]:
### Prediction
ypred = model.predict(xtest)
ypred

array([107460.63513437, 127716.73904828,  42409.53774881,  98865.92530469,
        38662.98691225,  81051.17791902])

In [39]:
model.predict([[11,39]])  #person with 11 years experience and 39 as age

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([132629.42929326])

In [40]:
### R2 Score
from sklearn.metrics import r2_score
r2 = r2_score(ytest,ypred)
r2*100

98.97718138444172